/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class Cursor
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "mimas/Cursor.h"


/** ~Cursor()
 * 
 */
static int Cursor__Cursor(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub_checksdata_d(L, 1, "mimas.Cursor"));
    if (userdata->gc) {
      Cursor *self = (Cursor *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "__gc: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "__gc: Unknown exception");
  }
  return dub_error(L);
}

/** Cast (class_name)
 * 
 */
static int Cursor__cast_(lua_State *L) {

  Cursor *self = *((Cursor **)dub_checksdata_n(L, 1, "mimas.Cursor"));
  const char *key = luaL_checkstring(L, 2);
  void **retval__ = (void**)lua_newuserdata(L, sizeof(void*));
  int key_h = dub_hash(key, 2);
  switch(key_h) {
    case 0: {
      if (DUB_ASSERT_KEY(key, "mimas.QCursor")) break;
      *retval__ = static_cast<QCursor *>(self);
      return 1;
    }
  }
  return 0;
}

/** Cursor::Cursor()
 * include/mimas/Cursor.h:43
 */
static int Cursor_Cursor(lua_State *L) {
  try {
    int top__ = lua_gettop(L);
    if (top__ >= 1) {
      int shape = dub_checkint(L, 1);
      Cursor *retval__ = new Cursor(shape);
      dub_pushudata(L, retval__, "mimas.Cursor", true);
      return 1;
    } else {
      Cursor *retval__ = new Cursor();
      dub_pushudata(L, retval__, "mimas.Cursor", true);
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "new: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "new: Unknown exception");
  }
  return dub_error(L);
}



// --=============================================== __tostring
static int Cursor___tostring(lua_State *L) {
  Cursor *self = *((Cursor **)dub_checksdata_n(L, 1, "mimas.Cursor"));
  lua_pushfstring(L, "mimas.Cursor: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg Cursor_member_methods[] = {
  { "__gc"         , Cursor__Cursor       },
  { "_cast_"       , Cursor__cast_        },
  { "new"          , Cursor_Cursor        },
  { "__tostring"   , Cursor___tostring    },
  { "deleted"      , dub_isDeleted        },
  { NULL, NULL},
};


extern "C" int luaopen_mimas_Cursor(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "mimas.Cursor");
  // <mt>

  // register member methods
  luaL_register(L, NULL, Cursor_member_methods);
  // save meta-table in mimas
  dub_register(L, "mimas", "Cursor", "Cursor");
  // <mt>
  lua_pop(L, 1);
  return 0;
}
