/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class Label
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "mimas/Label.h"


/** Cast (class_name)
 * 
 */
static int Label__cast_(lua_State *L) {

  Label *self = *((Label **)dub_checksdata_n(L, 1, "mimas.Label"));
  const char *key = luaL_checkstring(L, 2);
  void **retval__ = (void**)lua_newuserdata(L, sizeof(void*));
  return 0;
}

/** Label::Label(const char *title=NULL)
 * include/mimas/Label.h:46
 */
static int Label_Label(lua_State *L) {
  try {
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      const char *title = dub_checkstring(L, 1);
      QWidget *parent = *((QWidget **)dub_checksdata(L, 2, "mimas.QWidget"));
      Label *retval__ = new Label(title, parent);
      retval__->pushobject(L, retval__, "mimas.Label", true);
      return 1;
    } else if (top__ >= 1) {
      const char *title = dub_checkstring(L, 1);
      Label *retval__ = new Label(title);
      retval__->pushobject(L, retval__, "mimas.Label", true);
      return 1;
    } else {
      Label *retval__ = new Label();
      retval__->pushobject(L, retval__, "mimas.Label", true);
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "Label: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "Label: Unknown exception");
  }
  return dub_error(L);
}

/** Label::~Label()
 * include/mimas/Label.h:53
 */
static int Label__Label(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub_checksdata_d(L, 1, "mimas.Label"));
    if (userdata->gc) {
      Label *self = (Label *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "~Label: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "~Label: Unknown exception");
  }
  return dub_error(L);
}

/** void Label::setAlignment(int align)
 * include/mimas/Label.h:56
 */
static int Label_setAlignment(lua_State *L) {
  try {
    Label *self = *((Label **)dub_checksdata(L, 1, "mimas.Label"));
    int align = dub_checkint(L, 2);
    self->setAlignment(align);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setAlignment: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setAlignment: Unknown exception");
  }
  return dub_error(L);
}



// --=============================================== __tostring
static int Label___tostring(lua_State *L) {
  Label *self = *((Label **)dub_checksdata_n(L, 1, "mimas.Label"));
  lua_pushfstring(L, "mimas.Label: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg Label_member_methods[] = {
  { "_cast_"       , Label__cast_         },
  { "new"          , Label_Label          },
  { "__gc"         , Label__Label         },
  { "setAlignment" , Label_setAlignment   },
  { "__tostring"   , Label___tostring     },
  { NULL, NULL},
};


extern "C" int luaopen_mimas_Label(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "mimas.Label");
  // <mt>

  // register member methods
  luaL_register(L, NULL, Label_member_methods);
  // save meta-table in mimas
  dub_register(L, "mimas", "Label");
  // <mt>
  lua_pop(L, 1);
  return 0;
}
