/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class Button
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "mimas/Button.h"


/** Cast (class_name)
 * 
 */
static int Button__cast_(lua_State *L) {

  Button *self = *((Button **)dub_checksdata_n(L, 1, "mimas.Button"));
  const char *key = luaL_checkstring(L, 2);
  void **retval__ = (void**)lua_newuserdata(L, sizeof(void*));
  return 0;
}

/** Button::Button(const char *title=NULL, QWidget *parent=NULL)
 * include/mimas/Button.h:51
 */
static int Button_Button(lua_State *L) {
  try {
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      const char *title = dub_checkstring(L, 1);
      QWidget *parent = *((QWidget **)dub_checksdata(L, 2, "mimas.QWidget"));
      Button *retval__ = new Button(title, parent);
      retval__->pushobject(L, retval__, "mimas.Button", true);
      return 1;
    } else if (top__ >= 1) {
      const char *title = dub_checkstring(L, 1);
      Button *retval__ = new Button(title);
      retval__->pushobject(L, retval__, "mimas.Button", true);
      return 1;
    } else {
      Button *retval__ = new Button();
      retval__->pushobject(L, retval__, "mimas.Button", true);
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "Button: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "Button: Unknown exception");
  }
  return dub_error(L);
}

/** Button::~Button()
 * include/mimas/Button.h:56
 */
static int Button__Button(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub_checksdata_d(L, 1, "mimas.Button"));
    if (userdata->gc) {
      Button *self = (Button *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "~Button: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "~Button: Unknown exception");
  }
  return dub_error(L);
}



// --=============================================== __tostring
static int Button___tostring(lua_State *L) {
  Button *self = *((Button **)dub_checksdata_n(L, 1, "mimas.Button"));
  lua_pushfstring(L, "mimas.Button: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg Button_member_methods[] = {
  { "_cast_"       , Button__cast_        },
  { "new"          , Button_Button        },
  { "__gc"         , Button__Button       },
  { "__tostring"   , Button___tostring    },
  { NULL, NULL},
};


extern "C" int luaopen_mimas_Button(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "mimas.Button");
  // <mt>

  // register member methods
  luaL_register(L, NULL, Button_member_methods);
  // save meta-table in mimas
  dub_register(L, "mimas", "Button");
  // <mt>
  lua_pop(L, 1);
  return 0;
}
